feat: user-friendly error messaging
This change introduces a new errors library we can use to surface
user-friendly error messaging. When user errors are used, the internal
technical details of the error message are not shown to the user unless
they run the command with the verbose option.

What the command will return now:

```shell
$ datumctl activity query
error: Authentication session has expired or refresh token is no longer valid.
Please re-authenticate using: `datumctl auth login`
```