feat: add version command
This commit adds `kubectl version` command to datumctl and it configures
goreleaser to correctly set the required variables.

```
./dist/datumctl_linux_386_sse2/datumctl version
Client Version: v0.10.1-SNAPSHOT-6d21716
Kustomize Version: v5.7.1
Server Version: v0.0.0-master+$Format:%H$
error: server version error: could not parse pre-release/metadata (-master+$Format:%H$) in version "v0.0.0-master+$Format:%H$"
```

As you can see kubectl fails as well so it looks something related to
the server itself?

```
kubectl --kubeconfig .ninja/kubeconfig version
Client Version: v1.34.3
Kustomize Version: v5.7.1
Server Version: v0.0.0-master+$Format:%H$
error: server version error: could not parse pre-release/metadata (-master+$Format:%H$) in version "v0.0.0-master+$Format:%H$"
```